[tool.uv.workspace]
members = [
    "packages/mcqpy-core",
    "packages/mcqpy-pdf",
    "packages/mcqpy-shiny",
]

[project]
name = "mcqpy"
version = "0.4.0"
description = "Umbrella CLI package for MCQPy"
readme = "README.md"
authors = [
    { name = "Mads-Peter", email = "machri@phys.au.dk" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "mcqpy-core[cli,yaml]>=0.2.0",
    "mcqpy-pdf>=0.2.0",
    "rich>=14.2.0",
    "rich-click>=1.9.3",
]

[tool.uv.sources]
mcqpy-core = { workspace = true }
mcqpy-pdf = { workspace = true }
mcqpy-shiny = { workspace = true }

[project.scripts]
mcqpy = "mcqpy.cli.main:main"

[build-system]
requires = ["uv_build>=0.8.18,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 88


[tool.pytest.ini_options]
testpaths = ["pytest/"]
addopts = [
  "--cov-report", "term",
  "--cov-report", "html:.coverage-html",
  "--cov-report", "xml:.coverage.xml",
  "--junitxml", ".report.xml",
  "--cov", "src/mcqpy",
  "--cov", "packages/mcqpy-core/src/mcqpy_core",
  "--cov", "packages/mcqpy-pdf/src/mcqpy_pdf",
  "--cov", "packages/mcqpy-shiny/src/mcqpy_shiny",
]

[tool.coverage.run]
omit = []

[dependency-groups]
dev = [
    "mcqpy-shiny>=0.1.1",
    "ruff>=0.14.10",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "shiny>=1.2.1",
    "shinylive>=0.8.5",
    "zensical>=0.0.27",
    "mkdocstrings-python>=1.15.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-autoapi>=0.4.0",
    "mkdocs-pdf>=0.1.2",
    "mkdocs-click>=0.9.0",
]
